title: "Sophie d'Espalungue"
author: "Sophie d'Espalungue"
description: "Sophie d'Espalungue | Personal Website"
url: "https://www.sophie.d.espalungue.xyz"
baseurl: "/math"
javascript_enabled: true
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  mathjax: 
    cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
collections:
  works:
    output: true
    permalink: /math/works/:name/
  talks:
    output: true
    permalink: /math/talks/:name/
  tags:
    output: true
    permalink: /math/tags/:name
